### ISSUE TITLE
Hi! 一个关于CG Image 占用内存的问题

### ISSUE THREAD

**Issue by xhzengAIB** [MakeZL/MLSelectPhoto#1]
你好！
以下[这行代码](https://github.com/MakeZL/MLSelectPhoto/blob/master/MLSelectPhoto/Classes/ViewControllers/MLSelectPhotoPickerViewController.m#L105)会存在一个CG Image对象，一直占用内存，官方文档是说了会自动释放，但是延迟了很久都不释放，比如你选择一张原图3M的图，选择了9张，重复以上操作，然后就crash了，请问怎么解决这个问题呢？

**Comment by MakeZL** [comment]
Hi , 感谢反馈问题。
可以尝试把代码放入到@autoreleasepool 试试看可以不，我这里测试有点麻烦..
        @autoreleasepool {
            ALAsset *asset = (ALAsset *)imageObj;
            return [UIImage imageWithCGImage:[[asset defaultRepresentation] fullScreenImage]];
        }

**Comment by xhzengAIB** [comment]
尝试过了，还是没有用处呢！

**Comment by MakeZL** [comment]
已经OK了，我改成列表获取thumb图，而不是原图了.

**Comment by xhzengAIB** [comment]
我觉得这个治标不治本的方法，如果需要把原图上传的话，那怎么办呢？

**Comment by xhzengAIB** [comment]
虽然可以通过获取data的，如果上传前，需要对原图进行裁剪，那怎么办呢？
