### ISSUE TITLE
UIImage *image = [MLSelectPhotoPickerViewController getImageWithImageObj:obj];为什么用这个方法获取的图片很不清晰

### ISSUE THREAD

**Issue by vivijialei** [MakeZL/MLSelectPhoto#13]

**Comment by rth211** [comment]
默认是缩略图，你可以选择原图，originImage。

**Comment by MakeZL** [comment]
@vivijialei rth211说的对, 默认是获取缩略图
`MLSelectPhotoAssets *asset = self.assets[indexPath.row];`
这样是获取原图; `[asset originImage];`
