### ISSUE TITLE
图片多选有bug,如设置为9张,当反复勾选和取消勾选时会超过9张

### ISSUE THREAD

**Issue by zhushanbo** [MakeZL/MLSelectPhoto#3]
图片多选有bug,如设置为9张,当反复勾选和取消勾选时会超过9张

**Comment by AcmenDong** [comment]
+1.代码如下：
 // 创建控制器
    MLSelectPhotoPickerViewController *pickerVc = [[MLSelectPhotoPickerViewController alloc] init];
    // 默认显示相册里面的内容SavePhotos
    // 默认最多能选9张图片
    pickerVc.minCount = 9;
    pickerVc.status = PickerViewShowStatusCameraRoll;
    [pickerVc showPickerVc:self];
触发条件：勾选之后要取消勾选。
另外在不设置miniCount值时无法勾选图片

**Comment by MakeZL** [comment]
谢谢，忘了说已经改好了。minCount我换成了maxCount，不用传默认是9张 :)
