### ISSUE TITLE
相片不能全部显示

### ISSUE THREAD

**Issue by neufeng** [MakeZL/MLSelectPhoto#4]
只有最近拍摄这个组，其它相册不显示

**Comment by MakeZL** [comment]
我这块没测出来，用微信或者QQ的也一样么？

**Comment by neufeng** [comment]
不显示的那一部分照片是通过itunes同步过来的，微信，QQ选照片可以看到

**Comment by neufeng** [comment]
IOS8以上有这个问题， Photos framework可以得到所有照片，Assets方式似乎获取不到同步到相册的照片

**Comment by MakeZL** [comment]
噢噢。我知道了，的确得更新库了。

**Comment by neufeng** [comment]
pod 还没同步么，search到的还是1.2.1

**Comment by zscorpio** [comment]
这个我也遇到了...

**Comment by MakeZL** [comment]
现在已经改好了，以前是获取allPhotos图片没有获取所有allAssets。但是在iCloud的相册没办法同步过来，大家如果有好的办法也可以
