### ISSUE TITLE
希望提供个方法修改navigationbar的颜色

### ISSUE THREAD

**Issue by takanashi-positive** [MakeZL/MLSelectPhoto#5]
除了直接修改MLSelectPhototCommon中的定义还有其他方法吗？

**Comment by MakeZL** [comment]
您可以直接将MLSelectPhotoNavigationViewController改成您自己的Navigation，或者你直接去MLSelectPhotoNavigationViewController.m 去改都可以

**Comment by takanashi-positive** [comment]
@MakeZL好的，不过这样我就没办法用pod管理了这个包了吧 T T

**Comment by MakeZL** [comment]
恩恩，建议可以给MLSelectPhotoNavigationViewController加个分类，重新load或者什么方法来改，这样耦合就比较低了。

**Comment by takanashi-positive** [comment]
@MakeZL 好的，谢谢！

**Comment by MakeZL** [comment]
:)
